### ISSUE TITLE
International System of Units, -c option, and font color for below 0 temperatures

### ISSUE THREAD

**Issue by RobertPaulson90** [apizzimenti/cli-weather#47]
* The -c option does not change the windspeed unit to km/h, but rather keeps it in mph.

* If possible - a way to configure the units, locations? US units are not my cup of tea, I much prefer SI.

* The dark blue color for below 0 in temperatures (in celcius) might be a little too dark - I, at least, cannot see it.

[Reposting](https://www.reddit.com/r/node/comments/5lkncu/cliweather_one_year_later/dbx2pny/?context=3) for a friend

**Comment by pizzimathy** [comment]
What version of the package are you running (you can check this by running `$ weather -h`)?

1. In v2.0.7, `-c` changes units to meters per second and Celsius degrees.
2. Yep, you can totally save any options you want. Here are some examples of how saving works:

`$ weather -a "London, England" -c` &rarr; produces weather with SI units from London.

`$ weather -a "London, England" -c -s` &rarr; produces the same as above, but *saves* the arguments you passed as defaults. Now when you run `$ weather`, the weather from London with SI units will be displayed by default.

`$ weather -a "Dublin, Ireland"` &rarr; the defaults from the line above will still be saved. However, the arguments passed to the program are now `$ weather -a "Dublin, Ireland" -c`. When an inputted argument conflicts with a saved one, the saved one gets deferred. So, in this situation, instead of `London, England` being the location, `Dublin, Ireland` is. However, if you just run `$ weather` without arguments, the default location's (London's) weather will be displayed.

`$ weather --clear` &rarr; this clears all default values.

3. Yeah, the color is hard to see. I'll try to find a different blue or turn off the text dimming.

Thanks for opening up an issue ticket! It's great to be able to interact with users and get feedback. I genuinely appreciate it, and if you need any more help or have suggestions for *anything*, you can contact me on GitHub or visit my website's contact page and get back to me there.

Thanks!

**Comment by RobertPaulson90** [comment]
@fredefl
