### ISSUE TITLE
--address is not working

### ISSUE THREAD

**Issue by luisdavim** [apizzimenti/cli-weather#50]
This is what I get:
```
$ weather -c -a Dublin

    Error:
    No location parameter was provided.

    If you feel that this is an error in the application's programming and not with your internet connection, please submit an issue ticket at
    https://github.com/apizzimenti/cli-weather/issues
```

**Comment by benjamincharity** [comment]
I'm seeing the same passing in a lat/long or a zip

**Comment by pizzimathy** [comment]
@luisdavim @benjamincharity Just saw this issue. I'll take a look.

**Comment by pizzimathy** [comment]
If there are any issues with the new geocoding api, let me know! It won't be as replete as Google's, sadly.

**Comment by arlidge** [comment]
Hi there, I am trying to get the weather using command 

weather -c -a -47.024173,168.005163 -v 

And it all works except it is returning the weather for West Virginia and Sometimes Michigan - But those Co-Ordinates are for a town in New Zealand, Wanaka to be specific. 

Also command : weather -c -a Auckland  -  returns no data (Auckland is in New Zealand) Yes we exist :P 

When I use the DarkSky api manually I get no issues and it returns as it should. Not sure what the issue is.

Please advise.
