### ISSUE TITLE
permission denied error when trying to write to node_modules

### ISSUE THREAD

**Issue by pizzimathy** [apizzimenti/cli-weather#9]
Whenever the `-s` command is passed, an EACCESS error is thrown. How to fix?

**Comment by pizzimathy** [comment]
This can be solved by running `sudo` before `weather -s`, but I don't think people are gonna want to run as admin

**Comment by wevanscfi** [comment]
This is only an issue if users are installing npm modules in a directory that they do not have permissions to write to. 

I usually just add 
prefix=/Users/user/npm

to ~/.npmrc

And then add /Users/user/npm/bin to my PATH

This installs all global npm modules to a directory to that your user owns, and prevents any of these kinds of permission problems. If you are ever using sudo when using npm you will probably run into issues down the road. 

That being said, because it is very common for users to install global node modules in the directory that they do not own, it is probably best to save the configs in such a way that will not break when that is the case.

**Comment by pizzimathy** [comment]
I'm trying to work out a solution with child processes running a sudo command and I'll branch it soon

**Comment by pizzimathy** [comment]
For now, I'll branch something and you guys can pull against it and I've published a new version where, if the `-s` argument is passed, it'll say something about running sudo
